dist: xenial
language: python
python:
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7"
  - "pypy3.6"
cache: pip
install:
  - pip install pipenv
  - PIPENV_VERBOSITY=-1 pipenv install --dev --ignore-pipfile
script:
  - pipenv run pytest --cov autoopt --cov-report term
after_success:
  - pipenv run coveralls
