dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install pipenv
  - PIPENV_VERBOSITY=-1 pipenv install --dev
script:
  - pipenv run pytest --cov autoopt --cov-report term
after_success:
  - pipenv run coveralls
