dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"
cache: pip
install:
  - pip install pipenv
  - PIPENV_VERBOSITY=-1 pipenv install --dev
script:
  - pipenv run pytest --cov autoopt --cov-report term
after_success:
  - pipenv run coveralls
