language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - pytest --cov autoopt --cov-report term-missing
after_success:
  - coveralls