name: Push

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run -a

  test:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install tox tox-gh-actions
      - name: Run the tests
        run: tox
      - name: Combine the coverage data
        run: tox -e coverage
      - name: Upload coverage to CodeCov
        if: ${{ matrix.os == ubuntu-latest && matrix.python-version == 3.9}}
        uses: codecov/codecov-action@v1
